import { join } from "node:path";
import {
  type ResidentLaunchVector,
  type ResidentServiceDefinition,
  type ResidentServiceIdentity,
  residentServiceFingerprint,
} from "../../domain/resident-service";

export const launchdManagedMarker = "Generated by Ziggy; managed resident service";

const boundedSeconds = (value: number | undefined, fallback: number): number =>
  Number.isFinite(value) ? Math.min(300, Math.max(1, Math.trunc(value ?? fallback))) : fallback;

export interface LaunchdServiceRenderOptions {
  readonly identity: ResidentServiceIdentity;
  readonly profilePath: string;
  readonly launchVector: ResidentLaunchVector;
  readonly home: string;
  readonly ziggyHome: string;
  readonly throttleSeconds?: number;
  readonly stopTimeoutSeconds?: number;
}

const xml = (value: string): string =>
  value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");

export const launchdDefinitionPath = (home: string, identity: ResidentServiceIdentity): string =>
  join(home, "Library", "LaunchAgents", `${identity.launchdLabel}.plist`);

export const launchdLogPaths = (ziggyHome: string, identity: ResidentServiceIdentity) => ({
  stdout: join(ziggyHome, "logs", "serve", `${identity.key}.stdout.log`),
  stderr: join(ziggyHome, "logs", "serve", `${identity.key}.stderr.log`),
});

export const renderLaunchdService = (
  options: LaunchdServiceRenderOptions,
): ResidentServiceDefinition => {
  const throttleSeconds = boundedSeconds(options.throttleSeconds, 10);
  const stopTimeoutSeconds = boundedSeconds(options.stopTimeoutSeconds, 30);
  const path = launchdDefinitionPath(options.home, options.identity);
  const logs = launchdLogPaths(options.ziggyHome, options.identity);
  const fingerprint = residentServiceFingerprint(
    JSON.stringify({
      manager: "launchd",
      identity: options.identity.launchdLabel,
      profilePath: options.profilePath,
      launchVector: options.launchVector,
      logs,
      throttleSeconds,
      stopTimeoutSeconds,
    }),
  );
  const argumentsXml = options.launchVector
    .map((argument) => `    <string>${xml(argument)}</string>`)
    .join("\n");
  const content = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- ${launchdManagedMarker} -->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${xml(options.identity.launchdLabel)}</string>
  <key>ProgramArguments</key>
  <array>
${argumentsXml}
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ThrottleInterval</key>
  <integer>${throttleSeconds}</integer>
  <key>ExitTimeOut</key>
  <integer>${stopTimeoutSeconds}</integer>
  <key>StandardOutPath</key>
  <string>${xml(logs.stdout)}</string>
  <key>StandardErrorPath</key>
  <string>${xml(logs.stderr)}</string>
  <key>ZiggyServiceIdentity</key>
  <string>${xml(options.identity.key)}</string>
  <key>ZiggyProfilePath</key>
  <string>${xml(options.profilePath)}</string>
  <key>ZiggyDefinitionFingerprint</key>
  <string>${fingerprint}</string>
</dict>
</plist>
`;
  return {
    manager: "launchd",
    identity: options.identity,
    profilePath: options.profilePath,
    launchVector: options.launchVector,
    path,
    fingerprint,
    content,
  };
};

export const launchdDomain = (uid: number): string => `gui/${uid}`;
export const launchdDomainLabel = (uid: number, identity: ResidentServiceIdentity): string =>
  `${launchdDomain(uid)}/${identity.launchdLabel}`;
export const launchdBootstrapCommand = (
  uid: number,
  definitionPath: string,
): ResidentLaunchVector => ["launchctl", "bootstrap", launchdDomain(uid), definitionPath];
export const launchdBootoutCommand = (
  uid: number,
  identity: ResidentServiceIdentity,
): ResidentLaunchVector => ["launchctl", "bootout", launchdDomainLabel(uid, identity)];
export const launchdKickstartCommand = (
  uid: number,
  identity: ResidentServiceIdentity,
): ResidentLaunchVector => ["launchctl", "kickstart", "-k", launchdDomainLabel(uid, identity)];
export const launchdStatusCommand = (
  uid: number,
  identity: ResidentServiceIdentity,
): ResidentLaunchVector => ["launchctl", "print", launchdDomainLabel(uid, identity)];
export const launchdLogsCommand = (
  paths: ReturnType<typeof launchdLogPaths>,
  follow: boolean,
): ResidentLaunchVector => [
  "tail",
  ...(follow ? ["-f"] : ["-n", "200"]),
  paths.stdout,
  paths.stderr,
];
