import { join } from "node:path";
import {
  type ResidentLaunchVector,
  type ResidentServiceDefinition,
  type ResidentServiceIdentity,
  residentServiceFingerprint,
} from "../../domain/resident-service";

export const systemdManagedMarker = "Generated by Ziggy; managed resident service";

const boundedSeconds = (value: number | undefined, fallback: number): number =>
  Number.isFinite(value) ? Math.min(300, Math.max(1, Math.trunc(value ?? fallback))) : fallback;

export interface SystemdServiceRenderOptions {
  readonly identity: ResidentServiceIdentity;
  readonly profilePath: string;
  readonly launchVector: ResidentLaunchVector;
  readonly home: string;
  readonly ziggyHome: string;
  readonly pathEnvironment?: string;
  readonly restartSeconds?: number;
  readonly stopTimeoutSeconds?: number;
}

const systemdString = (value: string, escapeDollar = false): string => {
  const escaped = value
    .replaceAll("\\", "\\\\")
    .replaceAll('"', '\\"')
    .replaceAll("\n", "\\n")
    .replaceAll("\r", "\\r")
    .replaceAll("\t", "\\t")
    .replaceAll("%", "%%");
  return `"${escapeDollar ? escaped.replaceAll("$", () => "$$") : escaped}"`;
};

export const systemdDefinitionPath = (home: string, identity: ResidentServiceIdentity): string =>
  join(home, ".config", "systemd", "user", identity.systemdUnit);

export const renderSystemdService = (
  options: SystemdServiceRenderOptions,
): ResidentServiceDefinition => {
  const restartSeconds = boundedSeconds(options.restartSeconds, 10);
  const stopTimeoutSeconds = boundedSeconds(options.stopTimeoutSeconds, 30);
  const pathEnvironment =
    options.pathEnvironment ??
    `${join(options.home, ".local", "bin")}:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin`;
  const path = systemdDefinitionPath(options.home, options.identity);
  const environment = {
    HOME: options.home,
    ZIGGY_HOME: options.ziggyHome,
    PATH: pathEnvironment,
  };
  const fingerprint = residentServiceFingerprint(
    JSON.stringify({
      manager: "systemd",
      identity: options.identity.systemdUnit,
      profilePath: options.profilePath,
      launchVector: options.launchVector,
      environment,
      restartSeconds,
      stopTimeoutSeconds,
    }),
  );
  const execStart = options.launchVector.map((argument) => systemdString(argument, true)).join(" ");
  const content = `# ${systemdManagedMarker}
# Ziggy-Service-Identity: ${options.identity.key}
# Ziggy-Profile-Path: ${options.profilePath.replaceAll("\n", "\\n").replaceAll("\r", "\\r")}
# Ziggy-Definition-Fingerprint: ${fingerprint}
[Unit]
Description=Ziggy resident service for ${options.identity.readableName}
StartLimitIntervalSec=60
StartLimitBurst=5

[Service]
Type=simple
ExecStart=${execStart}
Restart=always
RestartSec=${restartSeconds}
TimeoutStopSec=${stopTimeoutSeconds}
Environment=${systemdString(`HOME=${environment.HOME}`)}
Environment=${systemdString(`ZIGGY_HOME=${environment.ZIGGY_HOME}`)}
Environment=${systemdString(`PATH=${environment.PATH}`)}
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=default.target
`;
  return {
    manager: "systemd",
    identity: options.identity,
    profilePath: options.profilePath,
    launchVector: options.launchVector,
    path,
    fingerprint,
    content,
  };
};

export const systemdCommand = (
  verb: "daemon-reload" | "enable" | "disable" | "start" | "stop" | "restart" | "is-active",
  unit?: string,
): ResidentLaunchVector => ["systemctl", "--user", verb, ...(unit === undefined ? [] : [unit])];
export const systemdMainPidCommand = (unit: string): ResidentLaunchVector => [
  "systemctl",
  "--user",
  "show",
  "--property=MainPID",
  "--value",
  unit,
];
export const systemdLogsCommand = (unit: string, follow: boolean): ResidentLaunchVector => [
  "journalctl",
  "--user",
  "-u",
  unit,
  "--no-pager",
  ...(follow ? ["-f"] : []),
];
export const systemdLingerCommand = (user: string): ResidentLaunchVector => [
  "loginctl",
  "show-user",
  user,
  "-p",
  "Linger",
];
