#!/usr/bin/env bun
/* oxlint-disable ziggy-effect/no-native-promise-ownership -- pi-docs generator is a Bun CLI, not an Effect service */
import { createHash } from "node:crypto";
import { lstatSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const PINNED_VERSION = "0.84.1";
const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = join(repositoryRoot, "src/adapters/pi/generated/pi-docs.ts");
const packageRoot = join(repositoryRoot, "node_modules/@earendil-works/pi-coding-agent");
const generatedDir = dirname(outputPath);

const fail = (message) => {
  console.error(message);
  process.exit(1);
};

const posix = (value) => value.split(sep).join("/");

const importAlias = (logical) =>
  `file${logical
    .replace(/\.md$/u, "")
    .split(/[^a-zA-Z0-9]+/u)
    .filter((part) => part.length > 0)
    .map((part) => part.slice(0, 1).toUpperCase() + part.slice(1).toLowerCase())
    .join("")}`;

const quote = (value) => JSON.stringify(value);

const packageManifest = await Bun.file(join(packageRoot, "package.json")).json();
if (packageManifest.name !== "@earendil-works/pi-coding-agent") {
  fail("pi-docs generator requires @earendil-works/pi-coding-agent");
}
if (packageManifest.version !== PINNED_VERSION) {
  fail(
    `pi-docs generator requires @earendil-works/pi-coding-agent@${PINNED_VERSION}, found ${packageManifest.version}`,
  );
}

const collectMarkdown = (absolutePath, logical) => {
  const status = lstatSync(absolutePath);
  if (status.isSymbolicLink()) fail(`pi-docs generator rejected symlink: ${absolutePath}`);
  if (!status.isFile()) fail(`pi-docs generator expected a file: ${absolutePath}`);
  return {
    logical,
    absolutePath,
    importPath: posix(relative(generatedDir, absolutePath)),
    content: readFileSync(absolutePath, "utf8"),
  };
};

const readme = collectMarkdown(join(packageRoot, "README.md"), "README.md");
const docsRoot = join(packageRoot, "docs");
const docsStatus = lstatSync(docsRoot);
if (docsStatus.isSymbolicLink() || !docsStatus.isDirectory()) {
  fail("pi-docs generator expected a physical docs directory");
}

const docs = readdirSync(docsRoot)
  .filter((name) => name.endsWith(".md"))
  .sort((left, right) => left.localeCompare(right))
  .map((name) => collectMarkdown(join(docsRoot, name), `docs/${name}`));

const files = [readme, ...docs];
if (files.length < 2) fail("pi-docs generator found no pinned markdown");
if (new Set(files.map((file) => file.logical)).size !== files.length) {
  fail("pi-docs generator found duplicate logical names");
}

const fingerprint = createHash("sha256")
  .update(
    JSON.stringify({
      package: "@earendil-works/pi-coding-agent",
      version: PINNED_VERSION,
      files: files.map((file) => ({ logical: file.logical, content: file.content })),
    }),
  )
  .digest("hex");

const source = `// Generated by tooling/generate-pi-docs.mjs. Do not edit.
${files.map((file) => `import ${importAlias(file.logical)} from ${quote(file.importPath)} with { type: "file" };`).join("\n")}

export const PI_DOCS_PACKAGE = "@earendil-works/pi-coding-agent";
export const PI_DOCS_VERSION = ${quote(PINNED_VERSION)};
export const PI_DOCS_FINGERPRINT = ${quote(fingerprint)};

export const PI_DOC_FILES = new Map<string, string>([
${files.map((file) => `  [${quote(file.logical)}, ${importAlias(file.logical)}],`).join("\n")}
]);
`;

if (process.argv.includes("--check")) {
  const current = Bun.file(outputPath);
  if (!(await current.exists()) || (await current.text()) !== source) {
    fail(`generated pi docs are stale: ${outputPath}`);
  }
  console.log(`pi docs fingerprint ${fingerprint}`);
  process.exit(0);
}

await Bun.write(outputPath, source);
console.log(`wrote pi docs fingerprint ${fingerprint}`);
